# Friedman Test
by: *Babak Zolghadr-Asli*

In [1]:
from scipy.stats import friedmanchisquare
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from pathlib import Path
import seaborn as sns
import os

%matplotlib inline

<div class="alert alert-danger">
    <b>SYNTAX GUIDE</b>
</div>

In order for this script/notebook to work, you need to store the files with a specified name-syntax;

* **Step I.** First all the files in specified folders, where the folder name is as the same as the algorithm name.
* **Step II.** If need be, pass the current direcoty that holds the files to `root_directory` as a `str` object; Note that if you are using a windows base machine you have to use `\` to seprate files location in your directory adress.  
* **Step III.** All results must be stored in a csv file, with the name `'a_fb_result.csv` where `a` is a placeholder for the **algorithm name**, and `b` is the number associated for the function. 



* Note that all these files should have a columns `best_OF`.

In [2]:
root_directory = 'C:/Users/bz267/Optimization results/Eliminate vs Preserve'

alg_list_temp = os.listdir(root_directory)
alg_list = [i for i in alg_list_temp if not i.startswith(tuple(str(i) for i in range(10)))]
print('=='*30)
print('The follwing algorithms are to be evaluted in this sessin:')
print('=='*30)
for i, alg_name in enumerate(alg_list):
    print('[%d] %s'%((i+1), alg_name))
print('--'*25)

============================================================
The follwing algorithms are to be evaluted in this sessin:
============================================================
[1] Eliminate_take_1
[2] Eliminate_take_2
[3] Eliminate_take_3
[4] Preserve_take_1
[5] Preserve_take_2
[6] Preserve_take_3
[7] Preserve_take_4
[8] Pure_Random
--------------------------------------------------

##### NC

In [3]:
func_num = np.arange(1, 31)

In [4]:
# RAEDING AND CREATING FILES WITH OFS OF ALL FUNCTIONS

for f in func_num:
    globals()['overall_db_f%d'%f] = pd.DataFrame(columns=alg_list)
    for a in alg_list:
        file_name = 'f%d.csv'%(f)
        folder_name = '/%s/NC/'%a
        db = pd.read_csv(root_directory+folder_name+file_name)
        exec("overall_db_f%d[a] = db['best_OF']"%f)
    exec("overall_db_f%d.dropna(inplace=True)"%f)

##### C

In [3]:
func_num = np.array([1, 2, 4, 6, 7])

In [4]:
# RAEDING AND CREATING FILES WITH OFS OF ALL FUNCTIONS

for f in func_num:
    globals()['overall_db_f%d'%f] = pd.DataFrame(columns=alg_list)
    for a in alg_list:
        file_name = 'f%d.csv'%(f)
        folder_name = '/%s/C/'%a
        db = pd.read_csv(root_directory+folder_name+file_name)
        exec("overall_db_f%d[a] = db['best_OF']"%f)
    exec("overall_db_f%d.dropna(inplace=True)"%f)

<div class="alert alert-success">
    <b>GENERAL PERFORMANCE ANALYSIS</b>
</div>

##### NC

In [5]:
std_result = pd.DataFrame(columns=alg_list)
mean_result = pd.DataFrame(columns=alg_list)
index = pd.Index(['f%d'%i for i in func_num])
for f in func_num:
    db = eval('overall_db_f%d'%f)
    std_temp = pd.DataFrame(db.std()).transpose()
    mean_temp = pd.DataFrame(db.mean()).transpose()
    std_result = pd.concat((std_result, std_temp), axis=0, ignore_index=True)
    mean_result = pd.concat((mean_result, mean_temp), axis=0, ignore_index=True)
std_result = std_result.set_index(index)
mean_result = mean_result.set_index(index)

In [6]:
mean_result

,Eliminate_take_1,Eliminate_take_2,Eliminate_take_3,Preserve_take_1,Preserve_take_2,Preserve_take_3,Preserve_take_4,Pure_Random
f1,2.376016e+10,2.165413e+10,4.246591e+09,8.727043e+06,3.176315e+06,2.284090e+06,1.876327e+06,1.200250e+10
f2,1.533851e+08,1.009718e+08,3.634528e+06,2.422154e+02,2.001660e+02,2.000977e+02,2.000697e+02,1.769376e+07
f3,6.885043e+03,6.081575e+03,4.516183e+03,3.027141e+02,3.010539e+02,3.007836e+02,3.006297e+02,4.188812e+03
f4,5.519487e+02,5.404589e+02,4.434104e+02,4.056287e+02,4.002599e+02,4.001124e+02,4.000900e+02,4.765870e+02
f5,5.519209e+02,5.503917e+02,5.458414e+02,5.309136e+02,5.130664e+02,5.124832e+02,5.130151e+02,5.466358e+02
f6,6.336438e+02,6.342016e+02,6.333178e+02,6.180817e+02,6.059961e+02,6.071183e+02,6.091900e+02,6.273093e+02
f7,8.556183e+02,8.554673e+02,8.198325e+02,7.734693e+02,7.354250e+02,7.288599e+02,7.276310e+02,8.176143e+02
f8,8.532077e+02,8.537720e+02,8.485129e+02,8.302443e+02,8.148912e+02,8.138282e+02,8.154727e+02,8.451260e+02
f9,1.534244e+03,1.494162e+03,1.508546e+03,1.190787e+03,9.202526e+02,9.284902e+02,9.972759e+02,1.257294e+03
f10,2.049621e+03,2.045111e+03,2.036567e+03,1.681499e+03,1.260702e+03,1.197427e+03,1.261692e+03,2.022136e+03
f11,1.287131e+03,1.272386e+03,1.210432e+03,1.135150e+03,1.108318e+03,1.104666e+03,1.103822e+03,1.220795e+03
f12,6.834335e+07,6.653131e+07,9.912854e+06,4.289662e+06,1.123569e+05,6.022974e+04,4.718442e+04,4.363458e+07
f13,4.777407e+04,3.827283e+04,8.220119e+03,1.541371e+04,2.630358e+03,2.251463e+03,2.109534e+03,3.596906e+04
f14,1.571114e+03,1.564971e+03,1.529818e+03,1.530106e+03,1.492196e+03,1.484915e+03,1.487131e+03,1.554849e+03
f15,2.169883e+03,2.065784e+03,1.816887e+03,1.909557e+03,1.734407e+03,1.716923e+03,1.706430e+03,2.063710e+03
f16,1.720562e+03,1.704108e+03,1.670237e+03,1.627150e+03,1.603457e+03,1.603007e+03,1.603053e+03,1.689888e+03
f17,1.841569e+03,1.840666e+03,1.803822e+03,1.770194e+03,1.730793e+03,1.724766e+03,1.722495e+03,1.810728e+03
f18,2.230795e+04,1.645137e+04,4.694165e+03,1.030873e+04,2.700491e+03,2.293791e+03,2.189204e+03,1.666595e+04
f19,2.446700e+03,2.278798e+03,2.025361e+03,2.159792e+03,1.972362e+03,1.953821e+03,1.947161e+03,2.287018e+03
f20,2.138660e+03,2.139231e+03,2.120042e+03,2.069874e+03,2.034141e+03,2.030267e+03,2.028132e+03,2.126780e+03
f21,2.221074e+03,2.216682e+03,2.218460e+03,2.196497e+03,2.177201e+03,2.158257e+03,2.178209e+03,2.210646e+03
f22,2.395248e+03,2.395827e+03,2.392077e+03,2.292152e+03,2.238916e+03,2.227955e+03,2.235086e+03,2.332099e+03
f23,2.652072e+03,2.649121e+03,2.635812e+03,2.606017e+03,2.562704e+03,2.480277e+03,2.462033e+03,2.549322e+03
f24,2.653786e+03,2.644570e+03,2.596640e+03,2.489469e+03,2.415446e+03,2.418923e+03,2.425565e+03,2.541738e+03
f25,3.054944e+03,3.044934e+03,2.958450e+03,2.931453e+03,2.698717e+03,2.611392e+03,2.596060e+03,2.994438e+03
f26,3.225802e+03,3.230419e+03,3.180060e+03,2.993385e+03,2.710921e+03,2.616427e+03,2.614001e+03,3.111800e+03
f27,3.123369e+03,3.119953e+03,3.106910e+03,3.103898e+03,3.093502e+03,3.091748e+03,2.996342e+03,3.120127e+03
f28,3.311208e+03,3.314330e+03,3.225853e+03,3.155132e+03,2.998946e+03,2.885165e+03,2.848153e+03,3.262613e+03
f29,3.304229e+03,3.302685e+03,3.258229e+03,3.218908e+03,3.155935e+03,3.120545e+03,3.093852e+03,3.280191e+03
f30,7.532505e+05,6.475144e+05,2.084313e+05,1.159461e+05,7.495892e+03,5.471997e+03,5.040348e+03,7.224450e+05

In [7]:
std_result

,Eliminate_take_1,Eliminate_take_2,Eliminate_take_3,Preserve_take_1,Preserve_take_2,Preserve_take_3,Preserve_take_4,Pure_Random
f1,7.299762e+09,6.514939e+09,1.265700e+09,2.443458e+06,813476.409444,590512.971553,403798.247979,3.073249e+09
f2,1.795042e+08,1.073648e+08,2.991772e+06,4.448559e+01,0.059804,0.034891,0.030228,1.691272e+07
f3,1.548201e+03,1.697734e+03,1.067443e+03,9.882030e-01,0.271448,0.175311,0.164813,8.937459e+02
f4,5.236341e+01,3.622082e+01,1.189953e+01,7.008803e+00,0.203419,0.034512,0.023462,1.664565e+01
f5,5.800792e+00,6.748393e+00,5.865468e+00,9.648674e+00,3.241052,2.981739,3.114159,6.422486e+00
f6,4.580036e+00,4.740935e+00,4.133482e+00,9.287344e+00,3.351178,3.605536,4.901379,3.499479e+00
f7,2.425786e+01,2.505187e+01,1.488383e+01,2.054474e+01,6.703638,4.901175,4.739555,1.435328e+01
f8,6.713762e+00,5.864182e+00,6.313653e+00,9.575893e+00,3.362648,2.709396,3.719483,5.060584e+00
f9,1.323174e+02,1.295836e+02,1.275584e+02,1.954127e+02,40.094198,50.269975,134.455228,9.472836e+01
f10,1.292606e+02,1.230722e+02,1.076660e+02,2.221909e+02,106.994221,88.107380,84.759475,1.060505e+02
f11,5.197681e+01,4.306364e+01,2.619779e+01,1.553189e+01,2.805397,1.657606,1.323051,2.248312e+01
f12,4.207488e+07,4.350165e+07,4.498026e+06,4.459847e+06,42560.467291,21552.350144,17494.695069,2.062582e+07
f13,3.564436e+04,2.794834e+04,4.537843e+03,1.060972e+04,507.686473,283.718578,226.727178,2.194864e+04
f14,3.563352e+01,3.047775e+01,1.813757e+01,3.166413e+01,18.135947,13.771649,15.663038,2.803392e+01
f15,3.599160e+02,2.465291e+02,8.409431e+01,2.061414e+02,82.415640,71.721808,69.942137,2.629095e+02
f16,3.561192e+01,3.757386e+01,2.177706e+01,3.838516e+01,1.266396,0.946489,0.813850,2.953563e+01
f17,3.160098e+01,3.504367e+01,1.942305e+01,2.980658e+01,5.703413,5.958921,5.671557,2.181858e+01
f18,1.275307e+04,8.505002e+03,1.394942e+03,7.775842e+03,509.899090,190.087366,132.402428,9.650100e+03
f19,3.640132e+02,2.012198e+02,6.164580e+01,1.806119e+02,30.745729,20.064336,14.732839,2.479626e+02
f20,2.458666e+01,2.310109e+01,1.965651e+01,2.519408e+01,6.970425,5.416993,4.656122,1.792476e+01
f21,1.129085e+01,1.284919e+01,9.873454e+00,2.217212e+01,42.153833,49.437720,41.453881,1.025217e+01
f22,4.564312e+01,5.314448e+01,6.117324e+01,2.496950e+01,10.881268,6.633131,10.681088,1.777498e+01
f23,2.468272e+01,2.614301e+01,3.977259e+01,9.701062e+01,119.001431,156.501268,155.314521,5.627530e+01
f24,5.192951e+01,4.843207e+01,3.332588e+01,3.302913e+01,30.433971,34.845429,40.446596,2.861559e+01
f25,4.441186e+01,3.263490e+01,1.611875e+01,5.635439e+01,118.367936,19.528117,33.748531,1.499563e+01
f26,7.661557e+01,6.396693e+01,5.046964e+01,1.014875e+02,106.712854,29.481022,20.235908,5.480245e+01
f27,6.689562e+00,6.446644e+00,1.677711e+01,6.310189e+00,2.440116,2.004207,161.616117,3.822660e+00
f28,3.515062e+01,3.784238e+01,2.127072e+01,6.083124e+01,130.283821,97.291395,39.391712,2.300958e+01
f29,4.621292e+01,4.309121e+01,2.783370e+01,4.603287e+01,16.727538,37.123305,28.548445,3.020296e+01
f30,4.665454e+05,4.830616e+05,1.240098e+05,1.916662e+05,2868.983801,1079.987229,763.241593,3.633356e+05

##### C

In [5]:
std_result = pd.DataFrame(columns=alg_list)
mean_result = pd.DataFrame(columns=alg_list)
index = pd.Index(['f%d'%i for i in func_num])
for f in func_num:
    db = eval('overall_db_f%d'%f)
    std_temp = pd.DataFrame(db.std()).transpose()
    mean_temp = pd.DataFrame(db.mean()).transpose()
    std_result = pd.concat((std_result, std_temp), axis=0, ignore_index=True)
    mean_result = pd.concat((mean_result, mean_temp), axis=0, ignore_index=True)
std_result = std_result.set_index(index)
mean_result = mean_result.set_index(index)

In [6]:
mean_result

,Eliminate_take_1,Eliminate_take_2,Eliminate_take_3,Preserve_take_1,Preserve_take_2,Preserve_take_3,Preserve_take_4,Pure_Random
f1,2.407988e+10,2.195379e+10,4.082831e+09,0.838749,0.357816,0.249690,0.226368,1.376861e+03
f2,1.503105e+08,1.273008e+08,4.058043e+06,18631.898489,36.793505,18.359509,37.322816,7.952718e+04
f4,5.586154e+02,5.395901e+02,4.441488e+02,0.539680,0.346354,0.287105,0.268004,2.015853e+01
f6,6.337337e+02,6.342776e+02,6.324429e+02,0.780000,0.000000,0.000000,0.000000,1.393590e+03
f7,8.587418e+02,8.570657e+02,8.143021e+02,0.887207,0.136305,0.074480,0.055490,2.010474e+06

In [7]:
std_result

,Eliminate_take_1,Eliminate_take_2,Eliminate_take_3,Preserve_take_1,Preserve_take_2,Preserve_take_3,Preserve_take_4,Pure_Random
f1,6.341530e+09,6.060699e+09,1.202257e+09,0.232749,0.093043,0.060627,0.054522,367.276637
f2,1.356764e+08,1.744155e+08,3.483117e+06,73392.633247,65.612052,46.490316,63.120897,91443.066784
f4,4.377454e+01,3.957885e+01,1.087069e+01,0.080079,0.039548,0.032675,0.035081,2.472497
f6,4.942257e+00,4.432675e+00,4.020732e+00,0.578748,0.000000,0.000000,0.000000,339.802827
f7,2.439099e+01,2.504061e+01,1.613383e+01,0.472659,0.060213,0.032976,0.023359,826648.210363

<div class="alert alert-warning">
    <b>Analysis</b>
</div>

##### NC

In [16]:
database = mean_result
temp_storage = list()
mean_analysis = pd.DataFrame(index=std_result.index)
for i in range(len(database)):
    np.argmin(database.iloc[i])
    min_val = np.min(database.iloc[i])
    index = database.iloc[i]==min_val
    temp_storage.append(list(index[index].index))
mean_analysis['Best Algorithms'] = temp_storage
mean_analysis['Best result'] = database.min(axis=1)
mean_analysis['Mean of algs'] = database.mean(axis=1)
mean_analysis['std. of algs'] = database.std(axis=1)
folder_name = '/0Summary result/Stat tests/NC/Mean & std comparision/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'mean_analysis.csv'
mean_analysis.to_csv(output_dir / file_name)

In [17]:
database = std_result
temp_storage = list()
std_analysis = pd.DataFrame(index=std_result.index)
for i in range(len(database)):
    np.argmin(database.iloc[i])
    min_val = np.min(database.iloc[i])
    index = database.iloc[i]==min_val
    temp_storage.append(list(index[index].index))
std_analysis['Best Algorithms'] = temp_storage
std_analysis['Best result'] = database.min(axis=1)
std_analysis['Mean of algs'] = database.mean(axis=1)
std_analysis['std. of algs'] = database.std(axis=1)
folder_name = '/0Summary result/Stat tests/NC/Mean & std comparision/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'std_analysis.csv'
std_analysis.to_csv(output_dir / file_name)

In [18]:
mean_analysis

       Best Algorithms   Best result  Mean of algs  std. of algs
f1   [Preserve_take_4]  1.876327e+06  7.709930e+09  1.014182e+10
f2   [Preserve_take_4]  2.000697e+02  3.446076e+07  5.921900e+07
f3   [Preserve_take_4]  3.006297e+02  2.859599e+03  2.860471e+03
f4   [Preserve_take_4]  4.000900e+02  4.523120e+02  6.403853e+01
f5   [Preserve_take_3]  5.124832e+02  5.330335e+02  1.786190e+01
f6   [Preserve_take_2]  6.059961e+02  6.211073e+02  1.248660e+01
f7   [Preserve_take_4]  7.276310e+02  7.892397e+02  5.492765e+01
f8   [Preserve_take_3]  8.138282e+02  8.343819e+02  1.781864e+01
f9   [Preserve_take_2]  9.202526e+02  1.228881e+03  2.627379e+02
f10  [Preserve_take_3]  1.197427e+03  1.694344e+03  3.957176e+02
f11  [Preserve_take_4]  1.103822e+03  1.180338e+03  7.674622e+01
f12  [Preserve_take_4]  4.718442e+04  2.411644e+07  3.039048e+07
f13  [Preserve_take_4]  2.109534e+03  1.908014e+04  1.870875e+04
f14  [Preserve_take_3]  1.484915e+03  1.526887e+03  3.536137e+01
f15  [Preserve_take_4]  1.706430e+03  1.897948e+03  1.822460e+02
f16  [Preserve_take_3]  1.603007e+03  1.652683e+03  4.920838e+01
f17  [Preserve_take_4]  1.722495e+03  1.780629e+03  5.050408e+01
f18  [Preserve_take_4]  2.189204e+03  9.701458e+03  7.916997e+03
f19  [Preserve_take_4]  1.947161e+03  2.133876e+03  1.882741e+02
f20  [Preserve_take_4]  2.028132e+03  2.085891e+03  5.047297e+01
f21  [Preserve_take_3]  2.158257e+03  2.197128e+03  2.348241e+01
f22  [Preserve_take_3]  2.227955e+03  2.313670e+03  7.508635e+01
f23  [Preserve_take_4]  2.462033e+03  2.574670e+03  7.429450e+01
f24  [Preserve_take_2]  2.415446e+03  2.523267e+03  1.004814e+02
f25  [Preserve_take_4]  2.596060e+03  2.861299e+03  1.936654e+02
f26  [Preserve_take_4]  2.614001e+03  2.960352e+03  2.715452e+02
f27  [Preserve_take_4]  2.996342e+03  3.094481e+03  4.144531e+01
f28  [Preserve_take_4]  2.848153e+03  3.125175e+03  1.892053e+02
f29  [Preserve_take_4]  3.093852e+03  3.216822e+03  8.353357e+01
f30  [Preserve_take_4]  5.040348e+03  3.081994e+05  3.392621e+05

In [19]:
std_analysis

        Best Algorithms    Best result  Mean of algs  std. of algs
f1    [Preserve_take_4]  403798.247979  2.269738e+09  3.060442e+09
f2    [Preserve_take_4]       0.030228  3.834670e+07  6.790772e+07
f3    [Preserve_take_4]       0.164813  6.510904e+02  7.393137e+02
f4    [Preserve_take_4]       0.023462  1.554995e+01  1.922539e+01
f5    [Preserve_take_3]       2.981739  5.477845e+00  2.298378e+00
f6    [Preserve_take_2]       3.351178  4.762421e+00  1.921627e+00
f7    [Preserve_take_4]       4.739555  1.442949e+01  8.378652e+00
f8    [Preserve_take_3]       2.709396  5.414950e+00  2.221389e+00
f9    [Preserve_take_2]      40.094198  1.130525e+02  5.027985e+01
f10   [Preserve_take_4]      84.759475  1.210127e+02  4.359697e+01
f11   [Preserve_take_4]       1.323051  2.062991e+01  1.926040e+01
f12   [Preserve_take_4]   17494.695069  1.440523e+07  1.877747e+07
f13   [Preserve_take_4]     226.727178  1.271338e+04  1.400959e+04
f14   [Preserve_take_3]      13.771649  2.393969e+01  8.410552e+00
f15   [Preserve_take_4]      69.942137  1.729587e+02  1.111718e+02
f16   [Preserve_take_4]       0.813850  2.073880e+01  1.716474e+01
f17   [Preserve_take_4]       5.671557  1.937834e+01  1.233150e+01
f18   [Preserve_take_4]     132.402428  5.113918e+03  5.093501e+03
f19   [Preserve_take_4]      14.732839  1.401245e+02  1.283896e+02
f20   [Preserve_take_4]       4.656122  1.593833e+01  8.847507e+00
f21  [Eliminate_take_3]       9.873454  2.493540e+01  1.669920e+01
f22   [Preserve_take_3]       6.633131  2.886260e+01  2.138527e+01
f23  [Eliminate_take_1]      24.682716  8.433768e+01  5.519621e+01
f24       [Pure_Random]      28.615593  3.763227e+01  8.532154e+00
f25       [Pure_Random]      14.995630  4.202001e+01  3.402473e+01
f26   [Preserve_take_4]      20.235908  6.297148e+01  3.106425e+01
f27   [Preserve_take_3]       2.004207  2.576333e+01  5.508689e+01
f28  [Eliminate_take_3]      21.270725  5.563393e+01  3.887720e+01
f29   [Preserve_take_2]      16.727538  3.447162e+01  1.045445e+01
f30   [Preserve_take_4]     763.241593  2.041663e+05  2.075982e+05

##### C

In [8]:
database = mean_result
temp_storage = list()
mean_analysis = pd.DataFrame(index=std_result.index)
for i in range(len(database)):
    np.argmin(database.iloc[i])
    min_val = np.min(database.iloc[i])
    index = database.iloc[i]==min_val
    temp_storage.append(list(index[index].index))
mean_analysis['Best Algorithms'] = temp_storage
mean_analysis['Best result'] = database.min(axis=1)
mean_analysis['Mean of algs'] = database.mean(axis=1)
mean_analysis['std. of algs'] = database.std(axis=1)
folder_name = '/0Summary result/Stat tests/C/Mean & std comparision/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'mean_analysis.csv'
mean_analysis.to_csv(output_dir / file_name)

In [9]:
database = std_result
temp_storage = list()
std_analysis = pd.DataFrame(index=std_result.index)
for i in range(len(database)):
    np.argmin(database.iloc[i])
    min_val = np.min(database.iloc[i])
    index = database.iloc[i]==min_val
    temp_storage.append(list(index[index].index))
std_analysis['Best Algorithms'] = temp_storage
std_analysis['Best result'] = database.min(axis=1)
std_analysis['Mean of algs'] = database.mean(axis=1)
std_analysis['std. of algs'] = database.std(axis=1)
folder_name = '/0Summary result/Stat tests/C/Mean & std comparision/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'std_analysis.csv'
std_analysis.to_csv(output_dir / file_name)

In [10]:
mean_analysis

,Best Algorithms,Best result,Mean of algs,std. of algs
f1,[Preserve_take_4],0.226368,6.264564e+09,1.045071e+10
f2,[Preserve_take_3],18.359509,3.522095e+07,6.424406e+07
f4,[Preserve_take_4],0.268004,1.954942e+02,2.659591e+02
f6,"[Preserve_take_2, Preserve_take_3, Preserve_ta...",0.000000,4.118530e+02,5.055437e+02
f7,[Preserve_take_4],0.055490,2.516257e+05,7.106822e+05

In [11]:
std_analysis

,Best Algorithms,Best result,Mean of algs,std. of algs
f1,[Preserve_take_4],0.054522,1.700561e+09,2.809607e+09
f2,[Preserve_take_3],46.490316,3.921750e+07,7.224649e+07
f4,[Preserve_take_3],0.032675,1.211049e+01,1.864587e+01
f6,"[Preserve_take_2, Preserve_take_3, Preserve_ta...",0.000000,4.422215e+01,1.194522e+02
f7,[Preserve_take_4],0.023359,1.033393e+05,2.922609e+05

<div class="alert alert-success">
<b>FRIEDMAN RANKING TEST</b>
</div>

<div class="alert alert-warning">
    <b>Part A: <i> Avr. Ranking </i> </b> 
</div>

##### NC

In [20]:
rank_db_raw = list()
for i in range(len(mean_result)):
    rankings = mean_result.iloc[i,:].rank(method='min')
    rank_db_raw.append(rankings)
mean_rank_db = pd.DataFrame(rank_db_raw, columns=mean_result.columns, index = mean_result.index).transpose()
mean_rank_db['Avr_rank'] = mean_rank_db.mean(axis=1)
mean_rank_db['Overall_rank'] = mean_rank_db['Avr_rank'].rank(method='min').astype(int)
folder_name = '/0Summary result/Stat tests/NC/Friedman test/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'mean_Friedmanrank_result.csv'
mean_rank_db.to_csv(output_dir / file_name)

In [21]:
mean_rank_db

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f23,f24,f25,f26,f27,f28,f29,f30,Avr_rank,Overall_rank
Eliminate_take_1,8.0,8.0,8.0,8.0,8.0,7.0,8.0,7.0,8.0,8.0,...,8.0,8.0,8.0,7.0,8.0,7.0,8.0,8.0,7.800000,8
Eliminate_take_2,7.0,7.0,7.0,7.0,7.0,8.0,7.0,8.0,6.0,7.0,...,7.0,7.0,7.0,8.0,6.0,8.0,7.0,6.0,7.000000,7
Eliminate_take_3,5.0,5.0,6.0,5.0,5.0,6.0,6.0,6.0,7.0,6.0,...,6.0,6.0,5.0,6.0,5.0,5.0,5.0,5.0,5.266667,5
Preserve_take_1,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.200000,4
Preserve_take_2,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,1.0,2.0,...,4.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.733333,3
Preserve_take_3,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.766667,2
Preserve_take_4,1.0,1.0,1.0,1.0,2.0,3.0,1.0,3.0,3.0,3.0,...,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.533333,1
Pure_Random,6.0,6.0,5.0,6.0,6.0,5.0,5.0,5.0,5.0,5.0,...,3.0,5.0,6.0,5.0,7.0,6.0,6.0,7.0,5.700000,6

##### C

In [12]:
rank_db_raw = list()
for i in range(len(mean_result)):
    rankings = mean_result.iloc[i,:].rank(method='min')
    rank_db_raw.append(rankings)
mean_rank_db = pd.DataFrame(rank_db_raw, columns=mean_result.columns, index = mean_result.index).transpose()
mean_rank_db['Avr_rank'] = mean_rank_db.mean(axis=1)
mean_rank_db['Overall_rank'] = mean_rank_db['Avr_rank'].rank(method='min').astype(int)
folder_name = '/0Summary result/Stat tests/C/Friedman test/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'mean_Friedmanrank_result.csv'
mean_rank_db.to_csv(output_dir / file_name)

In [13]:
mean_rank_db

                   f1   f2   f4   f6   f7  Avr_rank  Overall_rank
Eliminate_take_1  8.0  8.0  8.0  6.0  7.0       7.4             8
Eliminate_take_2  7.0  7.0  7.0  7.0  6.0       6.8             7
Eliminate_take_3  6.0  6.0  6.0  5.0  5.0       5.6             5
Preserve_take_1   4.0  4.0  4.0  4.0  4.0       4.0             4
Preserve_take_2   3.0  2.0  3.0  1.0  3.0       2.4             3
Preserve_take_3   2.0  1.0  2.0  1.0  2.0       1.6             2
Preserve_take_4   1.0  3.0  1.0  1.0  1.0       1.4             1
Pure_Random       5.0  5.0  5.0  8.0  8.0       6.2             6

<div class="alert alert-warning">
    <b>Part B: <i> Std. Ranking </i> </b> 
</div>

##### NC

In [22]:
rank_db_raw = list()
for i in range(len(std_result)):
    rankings = std_result.iloc[i,:].rank(method='min')
    rank_db_raw.append(rankings)
std_rank_db = pd.DataFrame(rank_db_raw, columns=std_result.columns, index = std_result.index).transpose()
std_rank_db['std_rank'] = std_rank_db.mean(axis=1)
std_rank_db['Overall_rank'] = std_rank_db['std_rank'].rank(method='min').astype(int)
folder_name = '/0Summary result/Stat tests/NC/Friedman test/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'std_Friedmanrank_result.csv'
std_rank_db.to_csv(output_dir / file_name)

In [23]:
std_rank_db

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f23,f24,f25,f26,f27,f28,f29,f30,std_rank,Overall_rank
Eliminate_take_1,8.0,8.0,7.0,8.0,4.0,5.0,7.0,7.0,6.0,7.0,...,1.0,8.0,6.0,6.0,6.0,3.0,8.0,7.0,6.533333,8
Eliminate_take_2,7.0,7.0,8.0,7.0,7.0,6.0,8.0,5.0,5.0,6.0,...,2.0,7.0,4.0,5.0,5.0,4.0,6.0,8.0,6.166667,7
Eliminate_take_3,5.0,5.0,6.0,5.0,5.0,4.0,5.0,6.0,4.0,5.0,...,3.0,4.0,2.0,3.0,7.0,1.0,2.0,4.0,4.300000,4
Preserve_take_1,4.0,4.0,4.0,4.0,8.0,8.0,6.0,8.0,8.0,8.0,...,5.0,3.0,7.0,7.0,4.0,6.0,7.0,5.0,5.766667,6
Preserve_take_2,3.0,3.0,3.0,3.0,3.0,1.0,3.0,2.0,1.0,4.0,...,6.0,2.0,8.0,8.0,2.0,8.0,1.0,3.0,3.433333,3
Preserve_take_3,2.0,2.0,2.0,2.0,1.0,3.0,2.0,1.0,2.0,2.0,...,8.0,5.0,3.0,2.0,1.0,7.0,5.0,2.0,2.700000,2
Preserve_take_4,1.0,1.0,1.0,1.0,2.0,7.0,1.0,3.0,7.0,1.0,...,7.0,6.0,5.0,1.0,8.0,5.0,3.0,1.0,2.666667,1
Pure_Random,6.0,6.0,5.0,6.0,6.0,2.0,4.0,4.0,3.0,3.0,...,4.0,1.0,1.0,4.0,3.0,2.0,4.0,6.0,4.433333,5

##### C

In [14]:
rank_db_raw = list()
for i in range(len(std_result)):
    rankings = std_result.iloc[i,:].rank(method='min')
    rank_db_raw.append(rankings)
std_rank_db = pd.DataFrame(rank_db_raw, columns=std_result.columns, index = std_result.index).transpose()
std_rank_db['std_rank'] = std_rank_db.mean(axis=1)
std_rank_db['Overall_rank'] = std_rank_db['std_rank'].rank(method='min').astype(int)
folder_name = '/0Summary result/Stat tests/C/Friedman test/'
output_dir = Path(root_directory+folder_name)
output_dir.mkdir(parents=True, exist_ok=True)
file_name = 'std_Friedmanrank_result.csv'
std_rank_db.to_csv(output_dir / file_name)

In [15]:
std_rank_db

                   f1   f2   f4   f6   f7  std_rank  Overall_rank
Eliminate_take_1  8.0  7.0  8.0  7.0  6.0       7.2             8
Eliminate_take_2  7.0  8.0  7.0  6.0  7.0       7.0             7
Eliminate_take_3  6.0  6.0  6.0  5.0  5.0       5.6             5
Preserve_take_1   4.0  4.0  4.0  4.0  4.0       4.0             4
Preserve_take_2   3.0  3.0  3.0  1.0  3.0       2.6             3
Preserve_take_3   2.0  1.0  1.0  1.0  2.0       1.4             1
Preserve_take_4   1.0  2.0  2.0  1.0  1.0       1.4             1
Pure_Random       5.0  5.0  5.0  8.0  8.0       6.2             6